const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "null"
const SESSION_ID = "PRABATH-MD~RmMxiQya#UnRkIlrU0Hzg8Vv9k4l-FA8lE68mjGfCdF7J2uS6R2Y"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
